import Foundation

struct BibleBook: Identifiable, Hashable { let id = UUID(); let name: String; let chapterCount: Int }

enum BibleData {
    static let oldTestament: [BibleBook] = [
        .init(name:"Genesis",chapterCount:50),.init(name:"Exodus",chapterCount:40),.init(name:"Leviticus",chapterCount:27),.init(name:"Numbers",chapterCount:36),.init(name:"Deuteronomy",chapterCount:34),.init(name:"Joshua",chapterCount:24),.init(name:"Judges",chapterCount:21),.init(name:"Ruth",chapterCount:4),.init(name:"1 Samuel",chapterCount:31),.init(name:"2 Samuel",chapterCount:24),.init(name:"1 Kings",chapterCount:22),.init(name:"2 Kings",chapterCount:25),.init(name:"1 Chronicles",chapterCount:29),.init(name:"2 Chronicles",chapterCount:36),.init(name:"Ezra",chapterCount:10),.init(name:"Nehemiah",chapterCount:13),.init(name:"Esther",chapterCount:10),.init(name:"Job",chapterCount:42),.init(name:"Psalms",chapterCount:150),.init(name:"Proverbs",chapterCount:31),.init(name:"Ecclesiastes",chapterCount:12),.init(name:"Song of Solomon",chapterCount:8),.init(name:"Isaiah",chapterCount:66),.init(name:"Jeremiah",chapterCount:52),.init(name:"Lamentations",chapterCount:5),.init(name:"Ezekiel",chapterCount:48),.init(name:"Daniel",chapterCount:12),.init(name:"Hosea",chapterCount:14),.init(name:"Joel",chapterCount:3),.init(name:"Amos",chapterCount:9),.init(name:"Obadiah",chapterCount:1),.init(name:"Jonah",chapterCount:4),.init(name:"Micah",chapterCount:7),.init(name:"Nahum",chapterCount:3),.init(name:"Habakkuk",chapterCount:3),.init(name:"Zephaniah",chapterCount:3),.init(name:"Haggai",chapterCount:2),.init(name:"Zechariah",chapterCount:14),.init(name:"Malachi",chapterCount:4)
    ]
    static let newTestament: [BibleBook] = [
        .init(name:"Matthew",chapterCount:28),.init(name:"Mark",chapterCount:16),.init(name:"Luke",chapterCount:24),.init(name:"John",chapterCount:21),.init(name:"Acts",chapterCount:28),.init(name:"Romans",chapterCount:16),.init(name:"1 Corinthians",chapterCount:16),.init(name:"2 Corinthians",chapterCount:13),.init(name:"Galatians",chapterCount:6),.init(name:"Ephesians",chapterCount:6),.init(name:"Philippians",chapterCount:4),.init(name:"Colossians",chapterCount:4),.init(name:"1 Thessalonians",chapterCount:5),.init(name:"2 Thessalonians",chapterCount:3),.init(name:"1 Timothy",chapterCount:6),.init(name:"2 Timothy",chapterCount:4),.init(name:"Titus",chapterCount:3),.init(name:"Philemon",chapterCount:1),.init(name:"Hebrews",chapterCount:13),.init(name:"James",chapterCount:5),.init(name:"1 Peter",chapterCount:5),.init(name:"2 Peter",chapterCount:3),.init(name:"1 John",chapterCount:5),.init(name:"2 John",chapterCount:1),.init(name:"3 John",chapterCount:1),.init(name:"Jude",chapterCount:1),.init(name:"Revelation",chapterCount:22)
    ]
}
